spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telnet?useUnicode=true&characterEncoding=utf8
    username: root
    password: zhs
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #redis的配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-wait: -1
      max-idle: 8
      min-idle: 0
      max-active: 8
# thymeleaf
  thymeleaf:
   prefix: classpath:/templates/
   check-template-location: true
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5
   cache: false




#mybatis
mybatis:
    type-aliases-package: com.zhs.pojo
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  port: 8888
#logging:
 # level:
  #   com.zhs.mapper : debug


# 七牛云配置
# bucket是创建的存储空间名
# path对应存储空间的访问域名
qiniu:
  accessKey: zHy3Im3Yjxxxxxx
  secretKey: LQR4mszxxxxxxxx
  bucket: xyz
  path: http://xxx.bkt.clouddn.com